package edu.metrostate.ics372.thatgroup.clinicaltrial.android.statemachine;

public enum ClinicalTrialEvent {
    ON_PREVIOUS,
    ON_EXIT,
    ON_OK,
    ON_CANCEL,
    ON_ERROR,
    ON_ADD,
    ON_SELECT,
    ON_VIEW,
    ON_UPDATE,
    ON_DELETE,
    ON_HOME,
    ON_IMPORT,
    ON_EXPORT,
    ON_CLINICS,
    ON_PATIENTS,
    ON_READINGS,
    ON_ACTIVE,
    ON_COMPLETE,
    ON_FAILED,
    ON_WITHDRAWN,
    ON_VIEW_READINGS,
    ON_ADD_READING,
    ON_IMPORT_FILE_INVALID,
    ON_IMPORT_BEGIN,
    ON_IMPORT_END,
    ON_EXPORT_BEGIN,
    ON_EXPORT_END
}
